name: Backend CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Changed from self-hosted to standard runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to v3

    - name: Build and run Docker Compose
      run: docker compose up --build -d

    - name: Wait for services to be healthy
      run: |
        docker compose ps
        # Add a delay to ensure services are fully up and running
        sleep 10

    - name: Run backend tests
      run: docker compose exec backend-api pytest tests/

    # CUSTOMIZE: Replace with your container registry
    # - name: Docker login to Harbor
    #   if: github.event_name == 'push'
    #   run: docker login your-registry.com -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
    #
    # - name: Tag and push backend-api image
    #   if: github.event_name == 'push'
    #   run: |
    #     docker tag project-backend-api your-registry.com/project/backend-api:latest
    #     docker tag project-backend-api your-registry.com/project/backend-api:1.0.0
    #     docker push your-registry.com/project/backend-api:latest
    #     docker push your-registry.com/project/backend-api:1.0.0